project_name: gkup
env_files:
  github_token: ~/.config/goreleaser/github_token

before:
  hooks:
    - go mod tidy

builds:
  - id: gkup-cli-build
    main: ./cmd/gkup-cli
    binary: gkup
    ldflags: -X github.com/Miguel-Dorta/gkup-cli/internal.Version={{.Version}}
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

archives:
  - id: gkup-cli-archive
    builds:
      - gkup-cli-build
    format: gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - none*